language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: surge
  project: ./build/
  domain: ephtracking-viz.surge.sh
  skip_cleanup: true
  on: master
